# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrsGDK8TSpkS3w0KbWPiYlDyTtCNhRou

# Data Preparation

## Import Libraries
"""

# Untuk manipulasi data
import pandas as pd
import numpy as np

# Untuk visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Untuk preprocessing & modelling klasik (sklearn)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error

# Untuk modelling Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

"""## Load Data"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("dansbecker/melbourne-housing-snapshot")

print("Path to dataset files:", path)

import pandas as pd
import os

csv_file_path = os.path.join(path, os.listdir(path)[0])

df = pd.read_csv(csv_file_path)

print(df.head())

df.info()

print("Jumlah baris:", df.shape[0])
print("Jumlah kolom:", df.shape[1])

"""## Data Cleaning and Type Conversion"""

# Konversi 'Date' menjadi datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print("Missing values sebelum ditangani:\n", df.isnull().sum())

"""# Handle Missing Value"""

# Drop baris yang harga (Price)-nya kosong (harus ada karena target)
df.dropna(subset=['Price'], inplace=True)

# Kolom penting: isi NaN dengan median
for col in ['Car', 'BuildingArea']:
    df[col].fillna(df[col].median(), inplace=True)

# Setelah pengisian, drop sisanya yang masih NaN (contoh: Date yang gagal parsing)
df.dropna(inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

# Cek ulang
print("Missing values setelah dibersihkan:\n", df.isnull().sum())

# Tipe data kolom numerik
num_cols = ['Rooms', 'Price', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Lattitude', 'Longtitude', 'Propertycount']
df[num_cols] = df[num_cols].astype(float)

# Cek tipe data terakhir
print(df.dtypes)

"""## Handle Duplicate Data"""

# Cek jumlah baris sebelum menghapus duplikat
before = df.shape[0]

# Cek apakah ada baris yang duplikat secara keseluruhan
duplicates = df.duplicated().sum()
print(f" Jumlah baris duplikat: {duplicates}")

# Hapus duplikat
df.drop_duplicates(inplace=True)

# Cek jumlah baris setelah penghapusan
after = df.shape[0]
print(f" Jumlah baris dihapus: {before - after}")
print(f" Total baris sekarang: {after}")

# Cek duplikat berdasarkan subset kolom penting
df.duplicated(subset=['Suburb', 'Rooms', 'Price', 'Distance', 'Landsize']).sum()

df.drop_duplicates(subset=['Suburb', 'Rooms', 'Price', 'Distance', 'Landsize'], inplace=True)

df.reset_index(drop=True, inplace=True)

"""
## Sort Data and Set Index"""

# Sort berdasarkan Price secara ascending (dari yang termurah ke termahal)
df.sort_values(by='Price', ascending=True, inplace=True)

# Reset index agar rapi setelah sorting
df.reset_index(drop=True, inplace=True)

# Cek 5 data teratas untuk verifikasi
print(df.head())

"""# Exploratory Data Analysis

## Summary
"""

print(df['Price'].describe())
sns.histplot(df['Price'], bins=50, kde=True)
plt.title('Distribution of Price')
plt.show()

"""## Analyze Numeric Features vs Price"""

num_features = ['Rooms', 'Distance', 'Landsize', 'BuildingArea', 'Bathroom', 'Car']

# Create a figure and a set of subplots
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.flatten() # Flatten the 2x3 grid to a 1D array for easy iteration

for i, col in enumerate(num_features):
    sns.scatterplot(x=df[col], y=df['Price'], ax=axes[i])
    axes[i].set_title(f'{col} vs Price')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Price')

# Remove any unused subplots if the number of features is less than the total number of plots
for j in range(len(num_features), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout() # Adjust layout to prevent titles/labels overlapping
plt.show()

corr = df[num_features + ['Price']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""Korelasi Mayoritas Positif: Sebagian besar fitur (Rooms, Landsize, BuildingArea, Bathroom, Car) menunjukkan korelasi positif dengan Price. Ini berarti, secara umum, semakin tinggi nilai fitur-fitur ini, semakin tinggi pula harga properti.
Korelasi Negatif untuk Jarak: Fitur Distance menunjukkan korelasi negatif dengan Price, yang berarti semakin jauh jarak properti, harganya cenderung lebih rendah.
Variabilitas Harga yang Tinggi: Untuk hampir semua fitur, terutama di nilai-nilai yang umum (misalnya 2-4 kamar, Landsize/BuildingArea kecil, 1-2 Car), terdapat variabilitas harga yang sangat tinggi. Ini mengindikasikan bahwa fitur tunggal tidak cukup untuk menjelaskan semua variasi harga. Harga properti dipengaruhi oleh kombinasi banyak faktor.
Konsentrasi Data: Sebagian besar data terkonsentrasi pada nilai-nilai fitur yang lebih umum (misalnya, Rooms 2-4, Distance dekat, Landsize/BuildingArea kecil, Bathroom 1-4, Car 1-2).
Potensi Outlier dan Data Sparsity:
Ada beberapa nilai ekstrem (Landsize/BuildingArea sangat besar, Distance sangat jauh) atau jumlah fitur yang sangat tinggi (Rooms, Bathroom, Car yang tinggi) yang hanya memiliki sedikit titik data (data sparsity).
Beberapa titik data terlihat seperti outlier (misalnya, properti dengan banyak kamar mandi tetapi harga rendah, atau properti yang sangat jauh tetapi harga tinggi). Ini perlu penyelidikan lebih lanjut, apakah itu data yang valid tetapi tidak biasa, atau kesalahan entri.

## Analyze Categorical Features vs Price
"""

cat_features = ['Regionname', 'Type', 'Suburb']

# Determine the number of rows and columns for the subplot grid
n_features = len(cat_features)
n_cols = 1 # You want them stacked in one column
n_rows = n_features # The number of rows equals the number of features

# Create a figure and a set of subplots
# Adjust the figure size to accommodate stacked plots
fig, axes = plt.subplots(n_rows, n_cols, figsize=(12, n_rows * 6)) # Adjust height multiplier as needed

# Flatten the axes array if there's more than one subplot
if n_features > 1:
    axes = axes.flatten()
else: # If only one subplot, axes is not an array
    axes = [axes] # Make it a list so the loop works

for i, col in enumerate(cat_features):
    sns.boxplot(x=df[col], y=df['Price'], ax=axes[i])
    axes[i].set_title(f'Price Distribution by {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Price')
    axes[i].tick_params(axis='x', rotation=45) # Rotate x-axis labels

plt.tight_layout() # Adjust layout to prevent titles/labels overlapping
plt.show()

top_suburbs = df['Suburb'].value_counts().nlargest(10).index
sns.boxplot(x=df[df['Suburb'].isin(top_suburbs)]['Suburb'], y=df['Price'])
plt.title('Price Distribution in Top 10 Suburbs')
plt.xticks(rotation=45)
plt.show()

"""Lokasi Adalah Raja: Ketiga plot ini secara konsisten menunjukkan bahwa lokasi (Regionname, Suburb) memiliki dampak yang sangat besar dan menjadi faktor paling dominan dalam menentukan harga properti. Bahkan dalam satu wilayah (Regionname), ada variasi harga yang signifikan antar Suburb.
Tipe Properti Memiliki Peran Penting: Selain lokasi, Type properti juga merupakan faktor penting yang membedakan harga secara substansial, dengan rumah tapak (h) secara umum lebih mahal.
Adanya Properti Mewah: Kehadiran outlier dengan harga sangat tinggi di kategori-kategori tertentu (terutama Southern Metropolitan, Eastern Metropolitan, tipe 'h', dan beberapa suburb spesifik) menunjukkan adanya segmen pasar properti mewah.
Kebutuhan Data Granular: Untuk prediksi harga yang akurat, model harus memperhitungkan variabel kategori ini, terutama Suburb, meskipun memerlukan penanganan khusus karena jumlah kategorinya yang banyak.

# Feature Engineering
"""

import pandas as pd

selected_features = [
    'Distance',
    'Propertycount',
    'Rooms',
    'Bathroom',
    'Car',
    'Landsize',
    'BuildingArea'
]

df_feature = df[selected_features].copy()

# Isi missing values dengan median
for col in selected_features:
    df_feature[col].fillna(df_feature[col].median(), inplace=True)

# Tambahan fitur rasio bangunan terhadap tanah
df_feature['Building_to_Land_Ratio'] = df_feature['BuildingArea'] / (df_feature['Landsize'] + 1)

# Target
y = df['Price']
X = df_feature

"""# Data Preprocessing

## Feature Selection

## Data Splitting
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## Data Scaling"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""# Modelling

## Modelling 1
"""

model_lr = LinearRegression()
model_lr.fit(X_train_scaled, y_train)
y_pred_lr = model_lr.predict(X_test_scaled)

# Evaluation Metrics
print("\n=== Linear Regression Evaluation ===")
print(f"MAE: {mean_absolute_error(y_test, y_pred_lr):.2f}")
print(f"RMSE: {mean_squared_error(y_test, y_pred_lr) ** 0.5:.2f}")
print(f"R^2: {r2_score(y_test, y_pred_lr):.2f}")
print(f"MAPE: {mean_absolute_percentage_error(y_test, y_pred_lr):.2f}%")

# Visualisasi Prediksi vs Aktual (scatter)
df_lr_compare = pd.DataFrame({'Actual Price': y_test, 'Predicted Price': y_pred_lr}).reset_index(drop=True)
plt.figure(figsize=(8,6))
sns.scatterplot(x='Actual Price', y='Predicted Price', data=df_lr_compare, alpha=0.6)
plt.plot([df_lr_compare['Actual Price'].min(), df_lr_compare['Actual Price'].max()],
         [df_lr_compare['Actual Price'].min(), df_lr_compare['Actual Price'].max()], 'r--')
plt.title("Linear Regression: Actual vs Predicted Price")
plt.grid(True)
plt.show()

# Visualisasi Distribusi
plt.figure(figsize=(8,6))
sns.histplot(df_lr_compare['Actual Price'], color='blue', label='Actual Price', kde=True, stat="density", bins=30, alpha=0.5)
sns.histplot(df_lr_compare['Predicted Price'], color='orange', label='Predicted Price', kde=True, stat="density", bins=30, alpha=0.5)
plt.title('Distribution of Actual vs Predicted Price (Linear Regression)')
plt.legend()
plt.grid(True)
plt.show()

"""## Modelling 2"""

model_dnn = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1)
])

model_dnn.compile(optimizer=Adam(learning_rate=0.001), loss='mse')

# Training
history = model_dnn.fit(X_train_scaled, y_train, validation_split=0.1,
                        epochs=100, batch_size=32, verbose=0)

# Predict
y_pred_dnn = model_dnn.predict(X_test_scaled).flatten()

# Evaluation Metrics
print("\n=== Deep Learning Evaluation ===")
print(f"MAE: {mean_absolute_error(y_test, y_pred_dnn):.2f}")
print(f"RMSE: {mean_squared_error(y_test, y_pred_dnn) ** 0.5:.2f}")
print(f"R^2: {r2_score(y_test, y_pred_dnn):.2f}")
print(f"MAPE: {mean_absolute_percentage_error(y_test, y_pred_dnn):.2f}%")

# Visualisasi Prediksi vs Aktual (scatter)
df_dnn_compare = pd.DataFrame({'Actual Price': y_test, 'Predicted Price': y_pred_dnn}).reset_index(drop=True)
plt.figure(figsize=(8,6))
sns.scatterplot(x='Actual Price', y='Predicted Price', data=df_dnn_compare, alpha=0.6)
plt.plot([df_dnn_compare['Actual Price'].min(), df_dnn_compare['Actual Price'].max()],
         [df_dnn_compare['Actual Price'].min(), df_dnn_compare['Actual Price'].max()], 'r--')
plt.title("DNN: Actual vs Predicted Price")
plt.grid(True)
plt.show()

# Visualisasi Distribusi
plt.figure(figsize=(8,6))
sns.histplot(df_dnn_compare['Actual Price'], color='blue', label='Actual Price', kde=True, stat="density", bins=30, alpha=0.5)
sns.histplot(df_dnn_compare['Predicted Price'], color='orange', label='Predicted Price', kde=True, stat="density", bins=30, alpha=0.5)
plt.title('Distribution of Actual vs Predicted Price (DNN)')
plt.legend()
plt.grid(True)
plt.show()

"""# Evaluation"""

def evaluate_model(y_true, y_pred, label='Model'):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred)

    print(f"Evaluasi {label}:")
    print(f"  MAE : {mae:.2f}")
    print(f"  MSE : {mse:.2f}")
    print(f"  RMSE: {rmse:.2f}")
    print(f"  R²  : {r2:.4f}")
    print(f"  MAPE: {mape:.4f}")

evaluate_model(y_test, y_pred_lr, "Linear Regression")
evaluate_model(y_test, y_pred_dnn, "Deep Learning")

def plot_predictions(y_true, y_pred, title='Prediksi vs Nilai Sebenarnya'):
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=y_true, y=y_pred, alpha=0.6)
    plt.plot([y_true.min(), y_true.max()], [y_true.min(), y_true.max()], 'r--')
    plt.xlabel('Actual Price')
    plt.ylabel('Prediction Price')
    plt.title(title)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

plot_predictions(y_test, y_pred_lr, 'Linear Regression')
plot_predictions(y_test, y_pred_dnn, 'Deep Neural Network')

df_comparison = pd.DataFrame({
    'Actual Price': y_test.reset_index(drop=True),
    'Predicted Price - Linear': y_pred_lr,
    'Predicted Price - DNN': y_pred_dnn
})

plt.figure(figsize=(14,6))
plt.plot(df_comparison['Actual Price'], label='Actual Price', color='blue', alpha=0.7)
plt.plot(df_comparison['Predicted Price - Linear'], label='Predicted Price - Linear', color='green', linestyle='--')
plt.plot(df_comparison['Predicted Price - DNN'], label='Predicted Price - DNN', color='orange', linestyle='--')
plt.title('Comparison: Actual Price vs Model Predictions')
plt.xlabel('Sample Index')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()